# Generated by Django 5.2.3 on 2025-09-14 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedschema_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='name',
        ),
    ]
