# Generated by Django 5.2.3 on 2025-09-14 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedschema_app', '0002_remove_tenant_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={},
        ),
        migrations.AlterModelManagers(
            name='tenant',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='password',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='username',
        ),
        migrations.AddField(
            model_name='tenant',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharedschema_app.tenant'),
        ),
    ]
