# Generated by Django 5.2.3 on 2025-09-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seperatedb_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='db_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
