# Generated by Django 5.2.3 on 2025-09-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seperatedb_app', '0002_tenant_db_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='db_name',
        ),
    ]
